[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/agendar"
  to = "/agendar.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200
